transaction_path: ''
A_n_fold: 100
bpr_batch: 2048
decay: 0.0001
lr: 0.001
layer: 3
seed: 42
dataset: "my_data"
topks: '[1,3,9]'
recdim: 64
dropout: 0
keep_prob: 0.6
test_u_batch_size: 100
path: "./checkpoints"
tensorboard: 1
comment: "lgn"
load: 0
epochs: 1000 
multicore: 1
cores: 20
pretrain: 0
model: 'lgn'
wandb: 0
wandb_name: 'LightGCN'